/**
 * Canonical Roles & Permission Definitions for SIH 2026 Crypto Fraud Attribution System
 */

const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  WORKSPACE_ADMIN: 'WORKSPACE_ADMIN',
  SENIOR_INVESTIGATOR: 'SENIOR_INVESTIGATOR',
  INVESTIGATOR: 'INVESTIGATOR',
  EXCHANGE_OFFICER: 'EXCHANGE_OFFICER',
  AUDITOR: 'AUDITOR',
  VICTIM: 'VICTIM'
});

const PERMISSIONS = Object.freeze({
  // Complaint & Case Management
  FILE_COMPLAINT: 'FILE_COMPLAINT',
  VIEW_OWN_CASE: 'VIEW_OWN_CASE',
  VIEW_WORKSPACE_CASES: 'VIEW_WORKSPACE_CASES',
  VIEW_ALL_CASES: 'VIEW_ALL_CASES',

  // Tracing & Forensic Analytics
  RUN_WALLET_TRACE: 'RUN_WALLET_TRACE',
  EXPORT_TRACE_GRAPH: 'EXPORT_TRACE_GRAPH',
  VIEW_VASP_ATTRIBUTION: 'VIEW_VASP_ATTRIBUTION',

  // Legal Notices & Freeze Orders
  DRAFT_FREEZE_NOTICE: 'DRAFT_FREEZE_NOTICE',
  APPROVE_FREEZE_NOTICE: 'APPROVE_FREEZE_NOTICE',
  ANCHOR_EVIDENCE_ONCHAIN: 'ANCHOR_EVIDENCE_ONCHAIN',
  FULFILL_FREEZE_ORDER: 'FULFILL_FREEZE_ORDER',
  UPLOAD_KYC_DOSSIER: 'UPLOAD_KYC_DOSSIER',

  // Administration & Governance
  MANAGE_OFFICERS: 'MANAGE_OFFICERS',
  MANAGE_WORKSPACES: 'MANAGE_WORKSPACES',
  TRIGGER_LOCKDOWN: 'TRIGGER_LOCKDOWN',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS'
});

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.WORKSPACE_ADMIN]: [
    PERMISSIONS.VIEW_WORKSPACE_CASES,
    PERMISSIONS.RUN_WALLET_TRACE,
    PERMISSIONS.EXPORT_TRACE_GRAPH,
    PERMISSIONS.VIEW_VASP_ATTRIBUTION,
    PERMISSIONS.DRAFT_FREEZE_NOTICE,
    PERMISSIONS.APPROVE_FREEZE_NOTICE,
    PERMISSIONS.ANCHOR_EVIDENCE_ONCHAIN,
    PERMISSIONS.MANAGE_OFFICERS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  [ROLES.SENIOR_INVESTIGATOR]: [
    PERMISSIONS.VIEW_WORKSPACE_CASES,
    PERMISSIONS.RUN_WALLET_TRACE,
    PERMISSIONS.EXPORT_TRACE_GRAPH,
    PERMISSIONS.VIEW_VASP_ATTRIBUTION,
    PERMISSIONS.DRAFT_FREEZE_NOTICE,
    PERMISSIONS.APPROVE_FREEZE_NOTICE,
    PERMISSIONS.ANCHOR_EVIDENCE_ONCHAIN,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  [ROLES.INVESTIGATOR]: [
    PERMISSIONS.VIEW_WORKSPACE_CASES,
    PERMISSIONS.RUN_WALLET_TRACE,
    PERMISSIONS.EXPORT_TRACE_GRAPH,
    PERMISSIONS.VIEW_VASP_ATTRIBUTION,
    PERMISSIONS.DRAFT_FREEZE_NOTICE
  ],
  [ROLES.EXCHANGE_OFFICER]: [
    PERMISSIONS.VIEW_VASP_ATTRIBUTION,
    PERMISSIONS.FULFILL_FREEZE_ORDER,
    PERMISSIONS.UPLOAD_KYC_DOSSIER
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.VIEW_ALL_CASES,
    PERMISSIONS.VIEW_VASP_ATTRIBUTION,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  [ROLES.VICTIM]: [
    PERMISSIONS.FILE_COMPLAINT,
    PERMISSIONS.VIEW_OWN_CASE
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
